# Generated by Django 4.2.5 on 2023-10-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
