# Generated by Django 4.2.5 on 2023-10-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_personal', '0002_projects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
    ]
