# Generated by Django 4.2.5 on 2023-10-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_personal', '0003_remove_projects_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
